services:
  airflow-postgres:
    image: postgres:16
    container_name: silson_airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3-python3.11
    container_name: silson_airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: silson_legal_db
      DB_USER: silson
      DB_PASSWORD: silson_pw
      LAW_API_OC: ${LAW_API_OC}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./requirements-airflow.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow db migrate && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.9.3-python3.11
    container_name: silson_airflow_webserver
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: silson_legal_db
      DB_USER: silson
      DB_PASSWORD: silson_pw
      LAW_API_OC: ${LAW_API_OC}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./requirements-airflow.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.9.3-python3.11
    container_name: silson_airflow_scheduler
    depends_on:
      - airflow-postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: silson_legal_db
      DB_USER: silson
      DB_PASSWORD: silson_pw
      LAW_API_OC: ${LAW_API_OC}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/opt/airflow/project
      - ./requirements-airflow.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"

volumes:
  airflow_postgres_data: